version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: conversys_fut_db
    restart: always
    environment:
      POSTGRES_USER: fut_user
      POSTGRES_PASSWORD: fut_password
      POSTGRES_DB: conversys_fut
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
